name-template: 'Release v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  ## Changes

  $CHANGES
